# Generated by Django 5.1 on 2024-11-19 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subcat', '0003_alter_subcategories_cat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tittle', models.CharField(max_length=100, unique=True)),
                ('Description', models.CharField(max_length=100, unique=True)),
                ('Actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Image', models.ImageField(upload_to='myimages/')),
                ('sub_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='subcat.subcategories')),
            ],
        ),
    ]
