# Generated by Django 5.1 on 2024-11-17 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('subcat', '0002_rename_catname_subcategories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='category.categories'),
        ),
    ]
