# Generated by Django 5.1 on 2024-11-19 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('subcat', '0003_alter_subcategories_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subcategories', to='category.categories'),
        ),
    ]
